metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.0.1.110, mac: '6c:4b:90:3e:3a:a9', disk: nvme0n1, network_interface: enp0s31f6}
#        metal0: {ansible_host: 10.0.1.110, mac: '6c:4b:90:63:eb:41', disk: sda, network_interface: enp0s31f6}
